"""Project-wide constants."""

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5050
MAX_MESSAGE_SIZE = 64 * 1024
SERVER_TICK_RATE = 10
BOARD_WIDTH = 30
BOARD_HEIGHT = 20
INITIAL_HEALTH = 100
MATCH_DURATION_TICKS = 600
MIN_PIE_COUNT = 1
SNAKE_COLOR_PRESETS = ("pink", "blue", "green", "orange", "purple", "yellow", "red")
